Repository jamessom/scms, pull requests merged in 2019-06, with the labels that each got.

#2 fix: start and docker-compose
  bin/start
  docker-compose.yml
Labels: bug

#3 Fix/model name
  app/controllers/api/v1/courses_controller.rb
  app/controllers/api/v1/employers_controller.rb
  app/controllers/api/v1/enrollments_controller.rb
  app/controllers/api/v1/enrrolments_controller.rb
  app/controllers/api/v1/grades_controller.rb
  app/controllers/api/v1/students_controller.rb
  app/controllers/api/v1/subjects_controller.rb
  app/controllers/api/v1/teachers_controller.rb
  app/controllers/api/v1/teams_controller.rb
  app/controllers/api/v1/trainers_controller.rb
  app/models/employer.rb
  app/models/enrollment.rb
  app/models/enrrolment.rb
  app/models/grade.rb
  app/models/subject.rb
  app/models/teacher.rb
  app/models/team.rb
  app/models/trainer.rb
  config/routes.rb
  db/migrate/20170326034952_create_students.rb
  db/migrate/20190611154350_rename_enrrolments_to_enrollments.rb
  db/migrate/20190611161602_rename_teams_to_grades.rb
  db/migrate/20190611162550_rename_courses_to_subjects.rb
  db/migrate/20190611164944_create_employers.rb
  db/migrate/20190611165324_rename_trainers_to_teachers.rb
  db/migrate/20190611171327_add_employer_ref_to_teachers.rb
  db/schema.rb
  db/seeds/development.rb
Labels: bug, enhancement

#15 Feature/add tests interface
  .gitignore
  .rspec
  Gemfile
  lib/tasks/rspec_html.rake
  reports/.keep
  spec/factories/students.rb
  spec/rails_helper.rb
  spec/requests/v1/students_spec.rb
  spec/spec_helper.rb
  spec/support/factory_bot.rb
Labels: Configuration, Tests, enhancement

#17 Feature/update er model and Fix/model name
  Gemfile
  README.md
  app/models/employer.rb
  app/models/enrollment.rb
  app/models/grade.rb
  app/models/student.rb
  app/models/subject.rb
  app/models/teacher.rb
  db/migrate/20170326035828_create_teams.rb
  db/migrate/20170326035926_create_enrrolments.rb
  db/migrate/20190611161602_rename_teams_to_grades.rb
  db/migrate/20190611162550_rename_courses_to_subjects.rb
  db/schema.rb
  docs/schema_db_v1.png
  docs/schema_db_v2.png
  docs/schema_db_v3.png
  spec/factories/students.rb
Labels: bug, enhancement

#21 Feature/add gem cache #18
  .gitignore
  Dockerfile
  app/controllers/application_controller.rb
  bin/start
  config/routes.rb
  docker-compose.yml
Labels: Configuration, enhancement
